name: CustomComands
version: 1.0.0
main: com.gekojr.customcomands.CustomComands
api-version: '1.21'

commands:
  discord:
    description: Mostra il link del server Discord
    usage: /discord
    permission: customcomands.discord
  annuncio:
    description: Invia un annuncio a tutto il server
    usage: /annuncio <messaggio>
    permission: customcomands.annuncio

permissions:
  customcomands.discord:
    description: Permette di usare /discord
    default: true
  customcomands.annuncio:
    description: Permette di usare /annuncio
    default: op
