name: CustomComands
version: 1.0.0
main: com.gekojr.customcomands.CustomComands
api-version: '1.21'

commands:
  discord:
    description: Shows the server Discord link
    usage: /discord
    permission: customcomands.discord
  annuncio:
    description: Sends an announcement to the entire server
    usage: /annuncio <message>
    permission: customcomands.annuncio
  trade:
    description: Trade items with another player
    usage: /trade <player> | /trade accept | /trade deny

permissions:
  customcomands.discord:
    description: Allows the use of /discord
    default: true
  customcomands.annuncio:
    description: Allows the use of /annuncio
    default: op
